# Generated by Django 2.0.1 on 2018-02-15 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='지원서 양식 제목')),
                ('use_image', models.BooleanField(default=True, verbose_name='이미지 첨부 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_answer', models.CharField(max_length=50)),
                ('long_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.AdminResume')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('got_point', models.IntegerField()),
                ('full_point', models.IntegerField()),
                ('evaluation_text', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='질문')),
                ('is_short_answer', models.BooleanField(default=False, verbose_name='단답형 항목 만들기')),
                ('admin_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.AdminResume')),
            ],
        ),
        migrations.AddField(
            model_name='applicantresume',
            name='interview_rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiting.InterviewRating'),
        ),
        migrations.AddField(
            model_name='answer',
            name='applicant_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.ApplicantResume'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.Question'),
        ),
    ]
