# Generated by Django 2.0.1 on 2018-02-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0002_adminresume_bottom_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='long_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='short_answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
