# Generated by Django 2.0.1 on 2018-02-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0004_auto_20180221_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='short_answer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='applicantresume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='사진 첨부하기'),
        ),
    ]
