# Generated by Django 2.0.1 on 2018-02-20 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0005_auto_20180221_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('applicant_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.ApplicantResume')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='내용')),
                ('applicant_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.ApplicantResume')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiting.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='applicant_resume',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
