# Generated by Django 2.0.1 on 2018-02-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0006_auto_20180221_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/%Y/%m/%d/', verbose_name='사진 첨부하기'),
        ),
    ]
