# Generated by Django 2.0.1 on 2018-02-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0007_auto_20180226_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resume_img/%Y/%m/%d/', verbose_name='사진 첨부하기'),
        ),
    ]
