# Generated by Django 2.0.1 on 2018-02-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
    ]
