# Generated by Django 2.0.1 on 2018-02-03 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club_position'),
        ('member', '0002_remove_profile_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='absence',
            name='attendance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Attendance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_info', to='member.Member'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='club',
        ),
        migrations.AddField(
            model_name='profile',
            name='club',
            field=models.ManyToManyField(related_name='club_member', to='club.Club'),
        ),
    ]
