# Generated by Django 2.0.1 on 2018-02-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20180203_1647'),
        ('member', '0003_auto_20180203_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='club_member', to='club.Club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='member',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='member.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='club',
            field=models.ManyToManyField(related_name='club_profile', to='club.Club'),
        ),
    ]
