# Generated by Django 2.0.1 on 2018-02-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20180208_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='club',
        ),
        migrations.AlterField(
            model_name='member',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='member.Profile'),
        ),
    ]
