# Generated by Django 2.0.1 on 2018-02-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50, verbose_name='club name')),
                ('club_image', models.ImageField(upload_to='')),
                ('club_description', models.TextField(verbose_name='club description')),
            ],
        ),
        migrations.CreateModel(
            name='ClubRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_theme', models.CharField(max_length=30, verbose_name='main theme')),
                ('sub_theme', models.CharField(max_length=30, verbose_name='sub theme')),
                ('rule', models.TextField(verbose_name='rule')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club', to='club.Club')),
            ],
        ),
    ]
