# Generated by Django 2.0.1 on 2018-02-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_description',
            field=models.TextField(blank=True, null=True, verbose_name='club description'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/%Y/%m/%d/'),
        ),
    ]
