# Generated by Django 2.0.1 on 2018-02-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20180208_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_image',
            field=models.ImageField(blank=True, null=True, upload_to='club/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='position',
            field=models.BooleanField(default=False),
        ),
    ]
