# Generated by Django 2.0.1 on 2018-02-10 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0006_auto_20180208_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applylist_club', to='club.Club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applylist_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
