# Generated by Django 2.0.1 on 2018-02-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_auto_20180213_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubrule',
            name='sub_theme',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='sub theme'),
        ),
    ]
