# Generated by Django 2.0.1 on 2018-02-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_auto_20180214_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='동아리 설명'),
        ),
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='club/%Y/%m/%d/', verbose_name='동아리 이미지'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50, verbose_name='동아리 이름'),
        ),
        migrations.AlterField(
            model_name='clubrule',
            name='main_theme',
            field=models.CharField(max_length=30, verbose_name='회칙 항목 대분류'),
        ),
        migrations.AlterField(
            model_name='clubrule',
            name='rule',
            field=models.TextField(verbose_name='회칙 내용'),
        ),
        migrations.AlterField(
            model_name='clubrule',
            name='sub_theme',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='회칙 항목 소분류'),
        ),
    ]
