# Generated by Django 2.0.1 on 2018-04-16 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_event_calendar_not_null'),
        ('club', '0011_auto_20180226_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='calendar',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.Calendar'),
            preserve_default=False,
        ),
    ]
