# Generated by Django 2.0.1 on 2018-04-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_article_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='coordinate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='좌표'),
        ),
    ]
