# Generated by Django 2.0.2 on 2018-04-23 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20180420_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hit',
            field=models.ManyToManyField(blank=True, null=True, related_name='hit_article_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
