# Generated by Django 2.0.1 on 2018-02-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0010_auto_20180214_1146'),
        ('member', '0010_auto_20180219_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='일정 제목')),
                ('description', models.TextField(blank=True, verbose_name='일정 내용')),
                ('event_at', models.DateTimeField(verbose_name='일정 시간')),
                ('absent_member', models.ManyToManyField(to='member.Member')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
            ],
        ),
    ]
